sudo: required
services:
    - docker

before_install:
    - docker build -t rohit/react -f Dockerfile.dev .

script:
    - docker run -e CI=true rohit/react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "react"
    env: "React-env"
    bucket_name: "elasticbeanstalk-us-east-2-975314484390"
    bucket_path: "react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
